# Generated by Django 4.2.10 on 2026-03-06 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="对话标题"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后活跃时间"),
                ),
            ],
            options={
                "verbose_name": "对话记录",
                "verbose_name_plural": "对话记录",
                "db_table": "chat_conversation",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "用户提问"),
                            ("assistant", "AI回答"),
                            ("system", "系统提示词"),
                        ],
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "language",
                    models.CharField(
                        default="auto", max_length=20, verbose_name="语言类型"
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(default=0, verbose_name="消耗Token数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                        verbose_name="所属对话",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息明细",
                "verbose_name_plural": "消息明细",
                "db_table": "chat_message",
                "ordering": ["created_at"],
            },
        ),
    ]
