# Generated by Django 4.2.7 on 2026-04-12 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_conversation_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="JSON 格式存储的结构化摘要")),
                (
                    "last_summarized_message_id",
                    models.BigIntegerField(help_text="最后一条被纳入摘要的消息 ID"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="chat.conversation",
                    ),
                ),
            ],
        ),
    ]
