# Generated by Django 4.2.10 on 2026-04-22 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0003_conversationsummary"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBaseSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("source_file_name", models.CharField(max_length=255)),
                ("collection_name", models.CharField(max_length=100)),
                ("persist_directory", models.CharField(max_length=500)),
                ("bm25_index_path", models.CharField(max_length=500)),
                ("chunk_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kb_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="chat_knowle_user_id_6754e7_idx",
                    )
                ],
            },
        ),
    ]
