# Generated by Django 4.2.10 on 2026-04-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_knowledgebasesession"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebasesession",
            name="source_file_path",
            field=models.CharField(default="", max_length=500),
        ),
    ]
